package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// CancelReason cancel reason
// swagger:model CancelReason
type CancelReason struct {

	// reason
	Reason string `json:"reason,omitempty"`
}

// Validate validates this cancel reason
func (m *CancelReason) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
