package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// JobStatus job status
// swagger:model JobStatus
type JobStatus string

const (
	JobStatusCreated           JobStatus = "created"
	JobStatusQueued            JobStatus = "queued"
	JobStatusWaitingForDeps    JobStatus = "waiting_for_deps"
	JobStatusRunning           JobStatus = "running"
	JobStatusSucceeded         JobStatus = "succeeded"
	JobStatusFailed            JobStatus = "failed"
	JobStatusAbortedDepsFailed JobStatus = "aborted_deps_failed"
	JobStatusAbortedByUser     JobStatus = "aborted_by_user"
)

// for schema
var jobStatusEnum []interface{}

func init() {
	var res []JobStatus
	if err := json.Unmarshal([]byte(`["created","queued","waiting_for_deps","running","succeeded","failed","aborted_deps_failed","aborted_by_user"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		jobStatusEnum = append(jobStatusEnum, v)
	}
}

func (m JobStatus) validateJobStatusEnum(path, location string, value JobStatus) error {
	if err := validate.Enum(path, location, value, jobStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this job status
func (m JobStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateJobStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
