package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// NewWorkflowResponse new workflow response
// swagger:model NewWorkflowResponse
type NewWorkflowResponse struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// revision
	Revision int64 `json:"revision,omitempty"`

	// states
	States []*State `json:"states"`
}

// Validate validates this new workflow response
func (m *NewWorkflowResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStates(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewWorkflowResponse) validateStates(formats strfmt.Registry) error {

	if swag.IsZero(m.States) { // not required
		return nil
	}

	for i := 0; i < len(m.States); i++ {

		if swag.IsZero(m.States[i]) { // not required
			continue
		}

		if m.States[i] != nil {

			if err := m.States[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
