package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// NewWorkflowRequest new workflow request
// swagger:model NewWorkflowRequest
type NewWorkflowRequest struct {

	// name
	Name string `json:"name,omitempty"`

	// start at
	StartAt string `json:"startAt,omitempty"`

	// states
	States []*State `json:"states"`
}

// Validate validates this new workflow request
func (m *NewWorkflowRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStates(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewWorkflowRequest) validateStates(formats strfmt.Registry) error {

	if swag.IsZero(m.States) { // not required
		return nil
	}

	for i := 0; i < len(m.States); i++ {

		if swag.IsZero(m.States[i]) { // not required
			continue
		}

		if m.States[i] != nil {

			if err := m.States[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
