// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// SLErrorEquals s l error equals
//
// swagger:model SLErrorEquals
type SLErrorEquals string

// Validate validates this s l error equals
func (m SLErrorEquals) Validate(formats strfmt.Registry) error {
	return nil
}
