package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// StateResourceStatus state resource status
// swagger:model StateResourceStatus
type StateResourceStatus struct {

	// last updated
	LastUpdated strfmt.DateTime `json:"lastUpdated,omitempty"`

	// queued
	Queued int64 `json:"queued,omitempty"`

	// running
	Running int64 `json:"running,omitempty"`
}

// Validate validates this state resource status
func (m *StateResourceStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
