package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// State state
// swagger:model State
type State struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// end
	End bool `json:"end,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// next
	Next string `json:"next,omitempty"`

	// resource
	Resource string `json:"resource,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this state
func (m *State) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
