package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// TaskAttempt task attempt
// swagger:model TaskAttempt
type TaskAttempt struct {

	// container instance a r n
	ContainerInstanceARN string `json:"containerInstanceARN,omitempty"`

	// exit code
	ExitCode int64 `json:"exitCode,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// started at
	StartedAt strfmt.DateTime `json:"startedAt,omitempty"`

	// stopped at
	StoppedAt strfmt.DateTime `json:"stoppedAt,omitempty"`

	// task a r n
	TaskARN string `json:"taskARN,omitempty"`
}

// Validate validates this task attempt
func (m *TaskAttempt) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
