// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WorkflowDefinitionOverrides workflow definition overrides
// swagger:model WorkflowDefinitionOverrides
type WorkflowDefinitionOverrides struct {

	// start at
	StartAt string `json:"StartAt,omitempty"`
}

// Validate validates this workflow definition overrides
func (m *WorkflowDefinitionOverrides) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowDefinitionOverrides) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowDefinitionOverrides) UnmarshalBinary(b []byte) error {
	var res WorkflowDefinitionOverrides
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
