// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WorkflowDefinitionRef workflow definition ref
// swagger:model WorkflowDefinitionRef

type WorkflowDefinitionRef struct {

	// name
	Name string `json:"name,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`
}

/* polymorph WorkflowDefinitionRef name false */

/* polymorph WorkflowDefinitionRef version false */

// Validate validates this workflow definition ref
func (m *WorkflowDefinitionRef) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowDefinitionRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowDefinitionRef) UnmarshalBinary(b []byte) error {
	var res WorkflowDefinitionRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
