package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// WorkflowQuery workflow query
// swagger:model WorkflowQuery
type WorkflowQuery struct {

	// limit
	Limit int32 `json:"limit,omitempty"`

	// statuses
	Statuses []string `json:"statuses"`
}

// Validate validates this workflow query
func (m *WorkflowQuery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatuses(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowQuery) validateStatuses(formats strfmt.Registry) error {

	if swag.IsZero(m.Statuses) { // not required
		return nil
	}

	return nil
}
