required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/Clever/aws-sdk-go-counter"
  revision = "6cdff7b1a4b593eafacf9c31ece8a830136f4125"

[[constraint]]
  name = "github.com/Clever/discovery-go"

[[constraint]]
  name = "github.com/Clever/go-process-metrics"

[[constraint]]
  name = "github.com/afex/hystrix-go"

[[require]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.0"

[[constraint]]
  name = "github.com/donovanhide/eventsource"

[[constraint]]
  name = "github.com/go-errors/errors"

[[constraint]]
  name = "github.com/go-openapi/errors"

[[constraint]]
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  name = "github.com/go-openapi/swag"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/mohae/deepcopy"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "^6.15.0"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.15.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"
