required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/Clever/aws-sdk-go-counter"
  branch = "master"

[[constraint]]
  name = "github.com/Clever/discovery-go"
  version = "v1.7.1"

[[constraint]]
  name = "github.com/Clever/go-process-metrics"
  branch = "master"

[[constraint]]
  name = "github.com/afex/hystrix-go"
  branch = "master"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.0"

[[constraint]]
  name = "github.com/donovanhide/eventsource"
  branch = "master"

[[constraint]]
  name = "github.com/go-errors/errors"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/errors"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/swag"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/validate"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  branch = "master"

[[constraint]]
  name = "github.com/kardianos/osext"
  branch = "master"

[[constraint]]
  name = "github.com/lightstep/lightstep-tracer-go"
  branch = "master"

[[constraint]]
  name = "github.com/mohae/deepcopy"
  branch = "master"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.10.0"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.15"
