ignored = [
  "github.com/elastic/go-elasticsearch",
  "github.com/elastic/go-elasticsearch/v6",
  "github.com/elastic/go-elasticsearch/v6/esapi",
  "github.com/elastic/go-elasticsearch/v6/estransport",
]
required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.38.0"

[[constraint]]
  name = "github.com/Clever/discovery-go"

[[constraint]]
  name = "github.com/Clever/go-process-metrics"

[[constraint]]
  name = "github.com/afex/hystrix-go"

[[constraint]]
  name = "github.com/donovanhide/eventsource"

[[constraint]]
  name = "github.com/go-errors/errors"

[[constraint]]
  name = "github.com/go-openapi/errors"

[[constraint]]
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  name = "github.com/go-openapi/swag"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  branch = "master"
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/gorilla/mux"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.1.1"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/mohae/deepcopy"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.7.0"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.27.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.1"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
