---
routes:

  # matchers for tracking Jobs/Workflows; prefix with `workflows.`
  # workflow-manager related matchers; prefix with workflow-mananger
  workflow-polling-alerts:
    matchers:
      title: ["polling-for-pending-workflows"]
      level: ["error"]
    output:
      type: "alerts"
      series: "workflow-manager.workflow-polling-error"
      dimensions: ["id"]
      stat_type: "counter"

  execution-not-found-alert:
    matchers:
      title: ["execution-not-found"]
    output:
      type: "alerts"
      series: "workflow-manager.execution-not-found"
      dimensions: ["workflow-id", "execution-id"]
      stat_type: "counter"
