---
routes:
  # workflow-manager related matchers; prefix with workflow-mananger

  workflow-polling-alerts:
    matchers:
      title: ["polling-for-pending-workflows"]
      level: ["error"]
    output:
      type: "alerts"
      series: "workflow-manager.workflow-polling-error"
      dimensions: ["id"]
      stat_type: "counter"

  execution-not-found-alert:
    matchers:
      title: ["execution-not-found"]
    output:
      type: "alerts"
      series: "workflow-manager.execution-not-found"
      dimensions: ["workflow-id", "execution-id"]
      stat_type: "counter"

  update-loop-lag-alert:
    matchers:
      title: ["pending-workflows-locked"]
    output:
      type: "alerts"
      series: "workflow-manager.update-loop-lag-seconds"
      value_field: "update-loop-lag-seconds"
      stat_type: "gauge"
      dimensions: []

  get-execution-history-counter:
    matchers:
      title: ["sfn-api-request-counters"]
    output:
      type: "alerts"
      series: "workflow-manager.get-execution-history-counter"
      stat_type: "counter"
      value_field: "get-execution-history"
      dimensions: []

  describe-execution-counter:
    matchers:
      title: ["sfn-api-request-counters"]
    output:
      type: "alerts"
      series: "workflow-manager.describe-execution-counter"
      stat_type: "counter"
      value_field: "describe-execution"
      dimensions: []
