---
routes:

  # matchers for tracking Jobs/Workflows; prefix with `workflows.`
  workflow-status-alerts:  # currently for batch only
    matchers:
      title: ["workflow-status-change"]
    output:
      type: "alerts"
      series: "workflows.workflow-error"
      dimensions: ["id", "name", "version"]
      # 0 for ongoing; 1 for failed; -1 for cancelled
      value_field: "value"
      stat_type: "gauge"
  job-status-alerts:  # currently for batch only
    matchers:
      title: ["job-status"]
    output:
      type: "alerts"
      series: "workflows.job-error"
      dimensions: ["id", "workflow", "state"]
      # 1 for failed; -1 for user abort; -2 for deps_abort
      # 0 for ongoing
      value_field: "value"
      stat_type: "gauge"

  # workflow-manager related matchers; prefix with workflow-mananger
  workflow-polling-alerts:
    matchers:
      title: ["polling-for-pending-workflows"]
      level: ["error"]
    output:
      type: "alerts"
      series: "workflow-manager.workflow-polling-error"
      dimensions: ["id"]
      stat_type: "counter"

  execution-not-found-alert:
    matchers:
      title: ["execution-not-found"]
    output:
      type: "alerts"
      series: "workflow-manager.execution-not-found"
      dimensions: ["workflow-id", "execution-id"]
      stat_type: "counter"
