---
routes:
  workflow-job-failed-metric:
    matchers:
      title: ["workflow-failed"]
    output:
      type: "alerts"
      series: "workflow-manager.job-failed"
      dimensions: ["workflow-name", "failed-job-name", "failed-job-resource", "workflow-version"]
      stat_type: "counter"

  execution-not-found-alert:
    matchers:
      title: ["execution-not-found"]
    output:
      type: "alerts"
      series: "workflow-manager.execution-not-found"
      dimensions: ["workflow-id", "execution-id"]
      stat_type: "counter"

  aws-sdk-go-counter:
    matchers:
      title: ["aws-sdk-go-counter"]
    output:
      type: "alerts"
      series: "aws-sdk-go.counter"
      stat_type: "counter"
      dimensions: ["aws-service", "aws-operation", "app"]

  post-unknown-workflow:
    matchers:
      title: ["start-unknown-workflow"]
    output:
      type: "notifications"
      channel: "#eng-infra-alerts-minor"
      icon: ":pipeline:"
      user: "workflow-manager"
      message: Attempted to start unknown workflow definition `%{name}` version `%{version}`

  zombie-execution-found:
    matchers:
      title: ["zombie-execution-found"]
    output:
      type: "notifications"
      channel: "#eng-infra-alerts-major"
      icon: ":pipeline:"
      user: "workflow-manager"
      message: Found zombie execution `%{execution-id}` for workflow `%{workflow-id}`. Check ticket https://clever.atlassian.net/browse/INFRANG-4733 for details
