swagger: '2.0'
info:
  title: workflow-manager
  description: Minimal Workflow orchestrator for AWS Batch
  version: 0.1.0
  x-npm-package: workflow-manager
schemes:
  - http
produces:
  - application/json
responses:
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/BadRequest"
  InternalError:
    description: "Internal Error"
    schema:
      $ref: "#/definitions/InternalError"
paths:
  /_health:
    get:
      operationId: healthCheck
      description: Checks if the service is healthy
      responses:
        200:
          description: OK response

  /workflows:
    post:
      operationId: newWorkflow
      summary: Create a new workflow
      schema:
        $ref: '#/definitions/NewWorkflowRequest'
      responses:
        201:
          description: Successful creation of a new workflow
          schema:
            $ref: '#/definitions/NewWorkflowResponse'

definitions:
  InternalError:
    type: object
    properties:
      message:
        type: string

  BadRequest:
    type: object
    properties:
      message:
        type: string

  NewWorkflowRequest:
    type: object
    properties:
      name: 
        type: string
      states:
        type: array
        items:
          $ref: '#/definitions/State'

  State:
    type: object
    properties:
      name: 
        type: string
      type: 
        type: string
      comment:
        type: string
      next:
        type: string
      resource:
        type: string
      end:
        type: boolean

  NewWorkflowResponse:
    type: object
    properties:
      id:
        type: string
      revision:
        type: integer
      name: 
        type: string
      states:
        type: array
        items:
          $ref: '#/definitions/State'
