swagger: '2.0'
info:
  title: workflow-manager
  description: Minimal Workflow orchestrator for AWS Batch
  version: 1.0.0
  x-npm-package: workflow-manager
schemes:
  - http
produces:
  - application/json

responses:
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/BadRequest"
  InternalError:
    description: "Internal Error"
    schema:
      $ref: "#/definitions/InternalError"
  NotFound:
    description: "Entity Not Found"
    schema:
      $ref: "#/definitions/NotFound"

paths:
  /_health:
    get:
      operationId: healthCheck
      description: Checks if the service is healthy
      responses:
        200:
          description: OK response

  /workflows:
    get:
      operationId: getWorkflows
      description: Get the latest versions of all available workflows
      responses:
        200:
          description: Successfully fetched all workflows
          schema:
            type: array
            items:
              $ref: '#/definitions/Workflow'
    post:
      operationId: newWorkflow
      summary: Create a new workflow
      parameters:
        - name: NewWorkflowRequest
          in: body
          schema:
            $ref: '#/definitions/NewWorkflowRequest'
      responses:
        201:
          description: Successful creation of a new workflow
          schema:
            $ref: '#/definitions/Workflow'

  /workflows/{name}:
    get:
      summary: Get a Workflow by Name
      operationId: getWorkflowByName
      parameters:
        - name: name
          in: path
          type: string
          required: true
        - name: version
          in: query
          type: integer
          required: false
        - name: latest
          in: query
          type: boolean
          required: false
          default: true
      responses:
        200:
          description: Workflows
          schema:
            type: array
            items:
              $ref: "#/definitions/Workflow"
        404:
          $ref: "#/responses/NotFound"
    put:
      operationId: updateWorkflow
      summary: Update an exiting workflow
      parameters:
        - name: NewWorkflowRequest
          in: body
          schema:
            $ref: '#/definitions/NewWorkflowRequest'
        - name: name
          in: path
          type: string
          required: true
      responses:
        201:
          description: Successful creation of a new workflow
          schema:
            $ref: '#/definitions/Workflow'
        404:
          $ref: "#/responses/NotFound"

  /jobs:
    post:
      summary: Start a job for a workflow
      operationId: startJobForWorkflow
      parameters:
        - name: input
          in: body
          schema:
            $ref: "#/definitions/JobInput"
      responses:
        200:
          description: Respond with Job Id and Name
          schema:
            $ref: "#/definitions/Job"
        404:
          $ref: "#/responses/NotFound"
    get:
      summary: Get summary of all active jobs for workflow
      operationId: getJobsForWorkflow
      parameters:
        - name: workflowName
          in: query
          type: string
          required: true
      responses:
        200:
          description: Job
          schema:
            type: array
            items:
              $ref: "#/definitions/Job"
        404:
          $ref: "#/responses/NotFound"

  /jobs/{jobId}:
    get:
      summary: Get details for the given jobId
      operationId: GetJob
      parameters:
        - name: jobId
          in: path
          type: string
          required: true
      responses:
        200:
          description: Job
          schema:
            $ref: "#/definitions/Job"
        404:
          $ref: "#/responses/NotFound"
    delete:
      summary: Cancel job with the jobId
      operationId: CancelJob
      parameters:
        - name: jobId
          in: path
          type: string
          required: true
        - name: reason
          in: body
          schema:
            $ref: "#/definitions/CancelReason"
          required: true
      responses:
        200:
          type: string
        404:
          $ref: "#/responses/NotFound"

definitions:
  InternalError:
    type: object
    properties:
      message:
        type: string

  BadRequest:
    type: object
    properties:
      message:
        type: string

  NotFound:
    type: object
    properties:
      message:
        type: string

  NewWorkflowRequest:
    type: object
    properties:
      name: 
        type: string
      startAt:
        type: string
      description:
        type: string
      states:
        type: array
        items:
          $ref: '#/definitions/State'

  State:
    type: object
    properties:
      name: 
        type: string
      type: 
        type: string
      comment:
        type: string
      next:
        type: string
      resource:
        type: string
      end:
        type: boolean

  Workflow:
    type: object
    properties:
      id:
        type: string
      revision:
        type: integer
      name: 
        type: string
      createdAt:
        type: string
        format: date-time
      startAt:
        type: string
      description:
        type: string
      states:
        type: array
        items:
          $ref: '#/definitions/State'

  Job:
    type: object
    properties:
      id:
        type: string
      createdAt:
        type: string
        format: date-time
      lastUpdated:
        type: string
        format: date-time
      workflow:
        $ref: '#/definitions/Workflow'
      status:
        type: string
      tasks:
        type: array
        items:
          $ref: '#/definitions/Task'

  Task:
    type: object
    properties:
      id:
        type: string
      createdAt:
        type: string
        format: date-time
      startedAt:
        type: string
        format: date-time
      stoppedAt:
        type: string
        format: date-time
      state:
        type: string
      status:
        type: string
      statusReason:
        type: string
      Container:
        type: string

  JobInput:
    type: object
    properties:
      workflow:
        $ref: '#/definitions/WorkflowRef'
      data:
        type: array

  WorkflowRef:
    type: object
    properties:
      name:
        type: string
      revision:
        type: integer

  CancelReason:
    type: object
    properties:
      reason:
        type: string
